set_codec:
  fields:
    codec:
      required: true
      selector:
        select:
          options:
            - flac
            - pcm
            - opus
            - vorbis

set_sampleformat:
  fields:
    sampleformat:
      required: true
      selector:
        select:
          options:
            - "48000:16:2"
            - "96000:16:2"
            - "192000:16:2"

set_buffer:
  fields:
    buffer_ms:
      required: true
      selector:
        number:
          min: 500
          max: 5000
          step: 100
          unit_of_measurement: ms
          mode: slider

delete_client:
  fields:
    client_id:
      required: true
      example: "00:21:6a:7d:74:fc"
      selector:
        text:
